"""Initial migration: create thumbtack_accounts and processed_leads tables

Revision ID: 3f1595bd7f7c
Revises: 
Create Date: 2025-11-04 14:18:10.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f1595bd7f7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thumbtack_accounts',
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_monitored_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_index(op.f('ix_thumbtack_accounts_account_id'), 'thumbtack_accounts', ['account_id'], unique=False)
    op.create_index(op.f('ix_thumbtack_accounts_email'), 'thumbtack_accounts', ['email'], unique=True)
    op.create_table('processed_leads',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('lead_key', sa.String(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_leads_account_id'), 'processed_leads', ['account_id'], unique=False)
    op.create_index('idx_processed_leads_account_lead', 'processed_leads', ['account_id', 'lead_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_processed_leads_account_lead', table_name='processed_leads')
    op.drop_index(op.f('ix_processed_leads_account_id'), table_name='processed_leads')
    op.drop_table('processed_leads')
    op.drop_index(op.f('ix_thumbtack_accounts_email'), table_name='thumbtack_accounts')
    op.drop_index(op.f('ix_thumbtack_accounts_account_id'), table_name='thumbtack_accounts')
    op.drop_table('thumbtack_accounts')
    # ### end Alembic commands ###

