# Generated by Django 5.2.6 on 2025-09-16 11:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AICall',
            fields=[
                ('agreed_address', models.CharField(blank=True, max_length=255, null=True)),
                ('agreed_contact_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('agreed_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('lead_key', models.CharField(db_index=True, max_length=64)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_phone', models.CharField(db_index=True, max_length=32)),
                ('from_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('user_timezone', models.CharField(default='America/New_York', max_length=64)),
                ('duration_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('finished', 'Finished'), ('error', 'Error')], default='pending', max_length=32)),
                ('provider_call_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('webhook_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
