# Generated by Django 5.2.6 on 2025-09-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Обработанный лид',
                'verbose_name_plural': 'Обработанные лиды',
            },
        ),
        migrations.CreateModel(
            name='FoundPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_key', models.CharField(db_index=True, max_length=64)),
                ('phone', models.CharField(db_index=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variables', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Найденный телефон',
                'verbose_name_plural': 'Найденные телефоны',
                'unique_together': {('lead_key', 'phone')},
            },
        ),
    ]
