# docker/Dockerfile.playwright
# образ уже содержит браузеры и всё нужное для Playwright
FROM mcr.microsoft.com/playwright/python:v1.54.0-jammy

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .


ENTRYPOINT ["sh", "/app/entrypoint.sh"]